//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\any_c\source\repos\practica basica\ProyectoEvaluacionParserV2\ProyectoEvaluacionParserV2\AUTOMATA.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AUTOMATAParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IAUTOMATAVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.automata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAutomata([NotNull] AUTOMATAParser.AutomataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.state"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitState([NotNull] AUTOMATAParser.StateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.transitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransitions([NotNull] AUTOMATAParser.TransitionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] AUTOMATAParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.state_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitState_name([NotNull] AUTOMATAParser.State_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.prop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProp([NotNull] AUTOMATAParser.PropContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.initial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitial([NotNull] AUTOMATAParser.InitialContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.acceptance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcceptance([NotNull] AUTOMATAParser.AcceptanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.transition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransition([NotNull] AUTOMATAParser.TransitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AUTOMATAParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] AUTOMATAParser.InputContext context);
}
